import type { Restaurant, MenuCategory, MenuItem } from '@/types/menu';

export const demoRestaurant: Restaurant = {
  id: 'demo-001',
  name: 'La Terraza Dorada',
  slug: 'la-terraza-dorada',
  description: 'Cocina contemporánea con alma latina. Sabores auténticos, presentación moderna.',
  logoUrl: '',
  coverUrl: '/images/restaurant_cover.png',
  phone: '+57 300 123 4567',
  address: 'Calle 10 #43-12, El Poblado',
  currency: 'COP',
  isActive: true,
  settings: {},
};

export const demoCategories: MenuCategory[] = [
  {
    id: 'cat-1',
    restaurantId: 'demo-001',
    name: 'Populares',
    icon: '🔥',
    sortOrder: 0,
    isActive: true,
  },
  {
    id: 'cat-2',
    restaurantId: 'demo-001',
    name: 'Entradas',
    icon: '🥗',
    sortOrder: 1,
    isActive: true,
  },
  {
    id: 'cat-3',
    restaurantId: 'demo-001',
    name: 'Platos Fuertes',
    icon: '🍖',
    sortOrder: 2,
    isActive: true,
  },
  {
    id: 'cat-4',
    restaurantId: 'demo-001',
    name: 'Hamburguesas',
    icon: '🍔',
    sortOrder: 3,
    isActive: true,
  },
  {
    id: 'cat-5',
    restaurantId: 'demo-001',
    name: 'Pizzas',
    icon: '🍕',
    sortOrder: 4,
    isActive: true,
  },
  {
    id: 'cat-6',
    restaurantId: 'demo-001',
    name: 'Bebidas',
    icon: '🍹',
    sortOrder: 5,
    isActive: true,
  },
  {
    id: 'cat-7',
    restaurantId: 'demo-001',
    name: 'Postres',
    icon: '🍰',
    sortOrder: 6,
    isActive: true,
  },
];

export const demoItems: MenuItem[] = [
  // Populares
  {
    id: 'item-1',
    categoryId: 'cat-1',
    restaurantId: 'demo-001',
    name: 'Bowl Teriyaki',
    description: 'Arroz jazmín, pollo teriyaki glaseado, edamame, aguacate, sésamo tostado y salsa ponzu.',
    price: 32900,
    imageUrl: '/images/bowl_teriyaki.png',
    isAvailable: true,
    isFeatured: true,
    sortOrder: 0,
    tags: ['popular', 'favorito'],
  },
  {
    id: 'item-2',
    categoryId: 'cat-1',
    restaurantId: 'demo-001',
    name: 'Burger Smash Doble',
    description: 'Doble smash patty 180g, queso cheddar fundido, cebolla caramelizada, pepinillos artesanales y salsa secreta.',
    price: 38900,
    imageUrl: '/images/burger_smash.png',
    isAvailable: true,
    isFeatured: true,
    sortOrder: 1,
    tags: ['popular', 'nuevo'],
  },
  {
    id: 'item-3',
    categoryId: 'cat-1',
    restaurantId: 'demo-001',
    name: 'Lomo en Costra de Café',
    description: 'Lomo fino 250g en costra de café colombiano, puré trufado, vegetales asados y demi-glace de vino tinto.',
    price: 54900,
    imageUrl: '/images/lomo_steak.png',
    isAvailable: true,
    isFeatured: true,
    sortOrder: 2,
    tags: ['popular', 'premium'],
  },
  // Entradas
  {
    id: 'item-4',
    categoryId: 'cat-2',
    restaurantId: 'demo-001',
    name: 'Carpaccio de Res',
    description: 'Finas láminas de res, rúcula, parmesano, alcaparras y vinagreta de limón.',
    price: 28900,
    imageUrl: '',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 0,
    tags: [],
  },
  {
    id: 'item-5',
    categoryId: 'cat-2',
    restaurantId: 'demo-001',
    name: 'Ceviche de Camarón',
    description: 'Camarones frescos en leche de tigre, cebolla morada, cilantro, maíz crocante y chips de camote.',
    price: 34900,
    imageUrl: '',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 1,
    tags: ['nuevo'],
  },
  {
    id: 'item-6',
    categoryId: 'cat-2',
    restaurantId: 'demo-001',
    name: 'Gyozas de Pollo',
    description: '6 unidades de dumplings al vapor con dip de soya, jengibre y aceite de sésamo.',
    price: 22900,
    imageUrl: '',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 2,
    tags: [],
  },
  // Platos Fuertes
  {
    id: 'item-7',
    categoryId: 'cat-3',
    restaurantId: 'demo-001',
    name: 'Risotto de Hongos',
    description: 'Arroz arborio cremoso con mix de hongos silvestres, parmesano y aceite de trufa.',
    price: 42900,
    imageUrl: '',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 0,
    tags: ['vegetariano'],
  },
  {
    id: 'item-8',
    categoryId: 'cat-3',
    restaurantId: 'demo-001',
    name: 'Salmón Glaseado',
    description: 'Filete de salmón glaseado en miso, espárragos, quinoa y salsa de maracuyá.',
    price: 49900,
    imageUrl: '',
    isAvailable: true,
    isFeatured: true,
    sortOrder: 1,
    tags: ['premium'],
  },
  {
    id: 'item-9',
    categoryId: 'cat-3',
    restaurantId: 'demo-001',
    name: 'Pollo al Horno',
    description: 'Medio pollo marinado en hierbas provenzales, papas rústicas y ensalada mediterránea.',
    price: 36900,
    imageUrl: '',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 2,
    tags: [],
  },
  // Hamburguesas
  {
    id: 'item-10',
    categoryId: 'cat-4',
    restaurantId: 'demo-001',
    name: 'Classic Burger',
    description: 'Carne angus 200g, lechuga, tomate, cebolla, pepinillos y salsa de la casa. Con papas fritas.',
    price: 29900,
    imageUrl: '/images/burger_smash.png',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 0,
    tags: [],
  },
  {
    id: 'item-11',
    categoryId: 'cat-4',
    restaurantId: 'demo-001',
    name: 'BBQ Bacon Burger',
    description: 'Carne angus 200g, bacon crocante, aros de cebolla, cheddar y salsa BBQ ahumada.',
    price: 35900,
    imageUrl: '/images/burger_smash.png',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 1,
    tags: ['popular'],
  },
  // Pizzas
  {
    id: 'item-12',
    categoryId: 'cat-5',
    restaurantId: 'demo-001',
    name: 'Margherita',
    description: 'Salsa San Marzano, mozzarella fresca, albahaca y aceite de oliva extra virgen.',
    price: 28900,
    imageUrl: '/images/pizza_margherita.png',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 0,
    tags: ['vegetariano'],
  },
  {
    id: 'item-13',
    categoryId: 'cat-5',
    restaurantId: 'demo-001',
    name: 'Pepperoni & Jalapeño',
    description: 'Salsa de tomate, mozzarella, pepperoni artesanal y jalapeños frescos.',
    price: 34900,
    imageUrl: '/images/pizza_margherita.png',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 1,
    tags: ['picante'],
  },
  // Bebidas
  {
    id: 'item-14',
    categoryId: 'cat-6',
    restaurantId: 'demo-001',
    name: 'Limonada de Coco',
    description: 'Limonada natural con leche de coco, hierbabuena y hielo.',
    price: 14900,
    imageUrl: '/images/limonada_coco.png',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 0,
    tags: [],
  },
  {
    id: 'item-15',
    categoryId: 'cat-6',
    restaurantId: 'demo-001',
    name: 'Mojito sin Alcohol',
    description: 'Menta fresca, limón, azúcar de caña y agua con gas.',
    price: 16900,
    imageUrl: '',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 1,
    tags: [],
  },
  {
    id: 'item-16',
    categoryId: 'cat-6',
    restaurantId: 'demo-001',
    name: 'Jugo Natural',
    description: 'Mango, maracuyá, lulo o fresa. En agua o en leche.',
    price: 12900,
    imageUrl: '',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 2,
    tags: [],
  },
  // Postres
  {
    id: 'item-17',
    categoryId: 'cat-7',
    restaurantId: 'demo-001',
    name: 'Brownie Volcán',
    description: 'Brownie tibio de chocolate belga con centro líquido, helado de vainilla y frutos rojos.',
    price: 19900,
    imageUrl: '',
    isAvailable: true,
    isFeatured: true,
    sortOrder: 0,
    tags: ['popular'],
  },
  {
    id: 'item-18',
    categoryId: 'cat-7',
    restaurantId: 'demo-001',
    name: 'Cheesecake de Maracuyá',
    description: 'Cheesecake cremoso con coulis de maracuyá y crumble de galleta.',
    price: 18900,
    imageUrl: '',
    isAvailable: true,
    isFeatured: false,
    sortOrder: 1,
    tags: [],
  },
];

export function formatPrice(price: number, currency: string = 'COP'): string {
  return new Intl.NumberFormat('es-CO', {
    style: 'currency',
    currency,
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(price);
}
